In [2]:
import numpy as np

In [11]:
np.zeros((100,3)) + np.ones((3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1

In [27]:
import time

width =  5
height = 2
aspect_ratio = float(width) / height
x0 = -1.0
x1 = 1.0
xstep = (x1 - x0) / (width - 1)
y0 = -1.0 / aspect_ratio
y1 = 1.0 / aspect_ratio
ystep = (y1 - y0) / (height - 1)

camera = np.array([0, 0, -1])

start = time.time()

pixelArray = np.zeros((width*height, 8))
pixelArray[:, 1:4] = camera

start2 = time.time()

positionArray = np.zeros((width*height,3))
positionArray[:, 0] = np.arange(0, width*height, 1)

positionArray[:,1] = positionArray[:,0] //  width

positionArray[:,0] = positionArray[:,0] % width
positionArray[:,0] = positionArray[:,0] * xstep + x0

positionArray[:,1] = positionArray[:,1] * ystep + y0

pixelArray[:, 4:7] = positionArray - camera

print(pixelArray[:, 4:7])
pixelArray[:, 4:7] =  pixelArray[:,4:7] / np.linalg.norm(pixelArray[:, 4:7], axis=1)[:, np.newaxis]
print(pixelArray[:, 4:7])

[[-1.  -0.4  1. ]
 [-0.5 -0.4  1. ]
 [ 0.  -0.4  1. ]
 [ 0.5 -0.4  1. ]
 [ 1.  -0.4  1. ]
 [-1.   0.4  1. ]
 [-0.5  0.4  1. ]
 [ 0.   0.4  1. ]
 [ 0.5  0.4  1. ]
 [ 1.   0.4  1. ]]
[[-0.68041382 -0.27216553  0.68041382]
 [-0.42107596 -0.33686077  0.84215192]
 [ 0.         -0.37139068  0.92847669]
 [ 0.42107596 -0.33686077  0.84215192]
 [ 0.68041382 -0.27216553  0.68041382]
 [-0.68041382  0.27216553  0.68041382]
 [-0.42107596  0.33686077  0.84215192]
 [ 0.          0.37139068  0.92847669]
 [ 0.42107596  0.33686077  0.84215192]
 [ 0.68041382  0.27216553  0.68041382]]


In [60]:

geods = np.zeros((1000,320*200,3))

geods[0,0] = np.array([4,0,0])
geods = np.linalg.norm(geods, axis=2) - 0
distances = np.linalg.norm(geods, axis=0)
intserects = np.where(distances > 0, 1, 0)
intserects


[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[4. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


array([1, 0, 0, ..., 0, 0, 0])

In [64]:
intserects.shape
intserects = intserects.reshape((320,200))
intserects.shape

(320, 200)